### ISSUE TITLE
调用buy不成功，有没有遇到过？？

### ISSUE THREAD

**Issue by Aireed** [hundsun/blockchain#1]
调用buy一起没有返回。把合约代码部署到mist钱包里执行，然后购买也不行。

**Comment by gelijie** [comment]
你好   我想问下这样的项目你是在什么开发环境下打开的   我现在想学习但是没有头绪  谢谢

**Comment by Aireed** [comment]
@gelijie    以太坊本地私有链开发环境搭建: http://ethfans.org/posts/ethereum-private-network-bootstrap#
更多资料可以搜索  “以太坊  私链开发”.

**Comment by Aireed** [comment]
是自己没有部署成功。现在可以了
